In [1]:
import torch
import torch.nn as nn

vocab_size = 8
embed_dim = 4
embedding = nn.Embedding(vocab_size, embed_dim)

custom_weights = torch.tensor( [[-0.1882,  0.5530,  1.6267,  0.7013],
                                [ 1.7840, -0.8278, -0.2701,  1.3586],
                                [ 1.0281, -1.9094,  0.3182,  0.4211],
                                [-1.3083, -0.0987,  0.7647, -0.3680],
                                [ 0.2293,  1.3255,  0.1318,  2.0501],
                                [ 0.4058, -0.6624, -0.8745,  0.7203],
                                [ 0.5582,  0.0786, -0.6817,  0.6902],
                                [ 0.4309, -1.3067, -0.8823,  1.5977]]).float()
embedding.weight = nn.Parameter(custom_weights)
print(embedding.weight)

Parameter containing:
tensor([[-0.1882,  0.5530,  1.6267,  0.7013],
        [ 1.7840, -0.8278, -0.2701,  1.3586],
        [ 1.0281, -1.9094,  0.3182,  0.4211],
        [-1.3083, -0.0987,  0.7647, -0.3680],
        [ 0.2293,  1.3255,  0.1318,  2.0501],
        [ 0.4058, -0.6624, -0.8745,  0.7203],
        [ 0.5582,  0.0786, -0.6817,  0.6902],
        [ 0.4309, -1.3067, -0.8823,  1.5977]], requires_grad=True)


In [2]:
data = torch.tensor([0, 4, 7, 2, 1], dtype=torch.long)
data_embedding = embedding(data)
print(data_embedding)

tensor([[-0.1882,  0.5530,  1.6267,  0.7013],
        [ 0.2293,  1.3255,  0.1318,  2.0501],
        [ 0.4309, -1.3067, -0.8823,  1.5977],
        [ 1.0281, -1.9094,  0.3182,  0.4211],
        [ 1.7840, -0.8278, -0.2701,  1.3586]], grad_fn=<EmbeddingBackward0>)


In [3]:
import torchsummary

embed_dim = 4
hidden_dim = 3
rnn = nn.RNN(embed_dim, hidden_dim, 
             batch_first=True, bias=False)
torchsummary.summary(rnn, data_embedding)

TypeError: rand(): argument 'size' failed to unpack the object at pos 2 with error "type must be tuple of ints,but got Tensor"

In [4]:
import torchsummary

embed_dim = 4
hidden_dim = 3
rnn = nn.RNN(embed_dim, 
             hidden_dim, 
             batch_first=True)
torchsummary.summary(rnn, data_embedding)

Layer (type:depth-idx)                   Output Shape              Param #
└─RNN: 0-1                               [-1, 3]                   27
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
└─RNN: 0-1                               [-1, 3]                   27
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Example

In [4]:
import torch
import torch.nn as nn

vocab_size = 8
embed_dim = 4
embedding = nn.Embedding(vocab_size, embed_dim)

custom_weights = torch.tensor( [[-0.1882,  0.5530,  1.6267,  0.7013],
                                [ 1.7840, -0.8278, -0.2701,  1.3586],
                                [ 1.0281, -1.9094,  0.3182,  0.4211],
                                [-1.3083, -0.0987,  0.7647, -0.3680],
                                [ 0.2293,  1.3255,  0.1318,  2.0501],
                                [ 0.4058, -0.6624, -0.8745,  0.7203],
                                [ 0.5582,  0.0786, -0.6817,  0.6902],
                                [ 0.4309, -1.3067, -0.8823,  1.5977]]).float()
embedding.weight = nn.Parameter(custom_weights)

data = torch.tensor([0, 4, 7, 2, 1], 
                    dtype=torch.long)
data_embedding = embedding(data)
print(data_embedding)

tensor([[-0.1882,  0.5530,  1.6267,  0.7013],
        [ 0.2293,  1.3255,  0.1318,  2.0501],
        [ 0.4309, -1.3067, -0.8823,  1.5977],
        [ 1.0281, -1.9094,  0.3182,  0.4211],
        [ 1.7840, -0.8278, -0.2701,  1.3586]], grad_fn=<EmbeddingBackward0>)


In [5]:
embed_dim = 4
hidden_dim = 3
rnn = nn.RNN(embed_dim, 
             hidden_dim,
             num_layers=1,
             batch_first=True)

rnn.bias_ih_l0 = nn.Parameter(torch.tensor([ 0.4481,  0.5537, -0.5006]).float())
rnn.bias_hh_l0 = nn.Parameter(torch.tensor([ 0.0135, -0.2209,  0.1330]).float())
rnn.weight_ih_l0 = nn.Parameter(torch.tensor([[-0.4174,  0.1953, -0.0365, -0.4025],
                                              [ 0.4722, -0.4085, -0.0236,  0.3763],
                                              [ 0.0550, -0.4921, -0.4307,  0.0855]]).float())
rnn.weight_hh_l0 = nn.Parameter(torch.tensor([[-0.5511,  0.1260,  0.0463],
                                              [-0.2291, -0.2084, -0.2352],
                                              [-0.4341, -0.2682,  0.0612]]).float())

In [6]:
test_data = data_embedding.reshape(1, 5, 4)
print(test_data.shape)

torch.Size([1, 5, 4])


In [7]:
rnn_output, rnn_hidden = rnn(test_data)

# (N, L, H_out)
print(rnn_output.shape) 
print(rnn_output)
print(rnn_output[:, -1, :])

torch.Size([1, 5, 3])
tensor([[[ 0.2973,  0.2388, -0.8593],
         [-0.3616,  0.6365, -0.8125],
         [-0.3297,  0.9502,  0.6365],
         [-0.1884,  0.9009,  0.4258],
         [-0.6319,  0.9454,  0.2323]]], grad_fn=<TransposeBackward1>)
tensor([[-0.6319,  0.9454,  0.2323]], grad_fn=<SliceBackward0>)


In [8]:
# (num_layers, N, H_out)
print(rnn_hidden.shape)  
print(rnn_hidden)
print(rnn_hidden[-1, :, :].shape)

torch.Size([1, 1, 3])
tensor([[[-0.6319,  0.9454,  0.2323]]], grad_fn=<StackBackward0>)
torch.Size([1, 3])


## Verify

In [11]:
data_embedding[0].reshape(4, 1).shape

torch.Size([4, 1])

In [12]:
h1 = torch.tanh(torch.matmul(rnn.weight_ih_l0, data_embedding[0]) + rnn.bias_ih_l0 + rnn.bias_hh_l0)
h1

tensor([ 0.2973,  0.2388, -0.8593], grad_fn=<TanhBackward0>)

In [13]:
h2 = torch.tanh(torch.matmul(rnn.weight_ih_l0, data_embedding[1]) + torch.matmul(rnn.weight_hh_l0, h1) + rnn.bias_ih_l0 + rnn.bias_hh_l0)
h2

tensor([-0.3616,  0.6365, -0.8125], grad_fn=<TanhBackward0>)