In [6]:
import torch
import torch.nn as nn

sequence_length = 5
embed_dim = 1
data = torch.tensor([1.2, 1.4, 2.1, 2.6, 3.5], 
                    dtype=torch.float)
print(data)

data = data.reshape(sequence_length, embed_dim)
print(data.shape)

tensor([1.2000, 1.4000, 2.1000, 2.6000, 3.5000])
torch.Size([5, 1])


In [7]:
hidden_dim = 2
rnn = nn.RNN(embed_dim, hidden_dim, batch_first=True)

rnn.bias_ih_l0 = nn.Parameter(torch.tensor([-0.5966,  0.0945]).float())
rnn.bias_hh_l0 = nn.Parameter(torch.tensor([ 0.6599, -0.2662]).float())
rnn.weight_ih_l0 = nn.Parameter(torch.tensor([[ 0.6584],
                                              [-0.1671]]).float())
rnn.weight_hh_l0 = nn.Parameter(torch.tensor([[ 0.5147, -0.1310],
                                              [ 0.6606, -0.1671]]).float())

In [8]:
rnn = nn.RNN(embed_dim, hidden_dim, num_layers=2, batch_first=True)
rnn_output, rnn_hidden = rnn(data)
rnn_output

tensor([[ 0.3583, -0.2994],
        [ 0.5818, -0.2590],
        [ 0.1358, -0.4469],
        [ 0.6254, -0.2196],
        [ 0.2193, -0.4074]], grad_fn=<SqueezeBackward1>)

In [9]:
rnn_hidden

tensor([[-0.6644, -0.1306],
        [ 0.2193, -0.4074]], grad_fn=<SqueezeBackward1>)